### PR TITLE
Define nodePackages as an extensible fixed point

### PR DESCRIPTION
**Pull request by ixmatus**
We also make the `generatePackages` utility function overridable with `makeOverridable` so that users can supply their own overrides following a similar convention to that of other language package sets.

This change _should_ be backwards compatible and we also honor the `extensions` argument with the caveat that anything provided via `overrides` will override packages given by the `extensions` argument to `generatePackages`.

#### Usage example

An example of what this change allows us to do, assuming we have generated a package set and that one of the npm packages in this set is named `to-array`. We also assume that the generated package for `to-array` is for the `0.1.4` version but what we really want is the `0.1.3` version. Therefore we want to override the `to-array` package and we also want all instances of that package as a dependency to be updated too.

Thus, we have an extensible overrides mechanism that also resembles what we see in other language-specific package sets:

```shell
# We are in the root of the output directory for `nixfromnpm`
$ tree .
.
├── default.nix
├── nodeLib
│   ├── buildNodePackage.nix
│   ├── circular_dependencies.md
│   ├── default.nix
│   ├── fetch.py
│   ├── fetchUrlNamespaced.nix
│   └── tools
│       ├── check-package-json
│       ├── install-binaries
│       └── patch-dependencies
├── nodePackages
│   ├── default.nix
│   ├── smallest
│   │   └── 1.0.1.nix
│   └── to-array
│       └── 0.1.4.nix
└── release.nix

5 directories, 13 files
```

... where `release.nix` is:

```nix
let

  pkgs = import <nixpkgs> { };
  generatedPackageSet = import ./default.nix { };

in

  generatedPackageSet.override {
    overrides = nodePackagesNew: nodePackagesOld: {
      to-array = nodePackagesOld.to-array.overrideNodePackage (oldAttrs: {
        version = "0.1.3";
        src = pkgs.fetchurl {
          url = "https://registry.npmjs.org/to-array/-/to-array-0.1.3.tgz";
          sha1 = "j54lzfyxxi8flks7507zc5rl6v3aspfl";
        };
      });
    };
  }
```

... we can see the overridden package is the result of building the `nodePackages.to-array` attribute:

```shell
$ nix-build --no-out-link --attr nodePackages.to-array ./release.nix
...
/nix/store/9zxzpmfm6knamb4k628b75z155kk9nw0-to-array-0.1.3-nodejs-8.9.4
```

Please note, in this usage example, `release.nix` was added in order to provide the example but this patch contains no change to `nixfromnpm` to generate such a file.

### CODE REVIEW

**Comment by ixmatus** [comment]
CC: @intractable @Gabriel439

**Comment by adnelson** [comment]
I’ll need to look it over in more detail but I like the idea here!

**Comment by adnelson** [comment]
This looks like a positive change. The only thing is If we're deprecating extensions passed in via a list, then we should update the Haskell code which generates the nix expressions for extensions to use the proper logic.

**Comment by ixmatus** [comment]
I figured we could do that in a follow-on PR that introduces the breaking change. As it stands, the extensions are still used so this is still backwards compatible with that feature while introducing the change to represent the package set as a fixed point that can be overridden downstream of generation (so, it's a nice rather than abrupt transition).

**Comment by ixmatus** [comment]
@adnelson thank you for the merge! We already use `nixfromnpm` to build `pulp` which we use to build purescript packages but now we'll be able to use it to build our entire front-end user interface (which is a mix of `npm` and `purescript`)!

**Comment by ixmatus** [comment]
@adnelson I think I got confused in my branches and testing somewhere; I broke this. I am fixing it right now (and tested). Sorry!

**Comment by ixmatus** [comment]
#98 addresses the issue I referenced above.

**Pull request merged**
