### PR TITLE
add a package with gyp to tests

### PR DESCRIPTION
**Pull request by adnelson**
I don't necessarily expect this to pass tests, but I'm curious.

### CODE REVIEW

**Comment by adnelson** [comment]
#122

**Comment by adnelson** [comment]
Hah. Ok so looks like maybe #115 is specifically about Darwin.

**Comment by ixmatus** [comment]
Weird. `fsevents` should not build on Linux because it is a macOS only package...

**Comment by ixmatus** [comment]
@adnelson do you know if npm provides any platform compatibility hints that could be added to the generated code so we could push errors like these upstream into evaluation?

**Comment by adnelson** [comment]
Yeah, there's an `os` key in the `package.json` which is mapped to `["darwin"]`. We're not checking that key; I suppose we could be. I have no idea why it builds on linux then. We should replace this test with a package that is actually meant to work with linux.

**Comment by adnelson** [comment]
I'm gonna rebase this guy onto latest master. It should fail then due to the `platforms` argument popping up.

**Comment by adnelson** [comment]
Cool, so that failed as expected. Good news and bad news hah. So we'll want to find a gyp package which works on linux and osx both.

**Comment by adnelson** [comment]
This doesn't seem necessary to keep any more, since the relevant issue have been fixed.

**Pull request closed without merging**
